<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>工具箱</AssemblyName>
    <ApplicationIcon>toolbox.ico</ApplicationIcon>
    <StartupObject>ToolboxCS.Program</StartupObject>
    <InvariantGlobalization>true</InvariantGlobalization>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Docnet.Core" Version="2.6.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="pdf.png" />
    <EmbeddedResource Include="toolbox.ico" />
  </ItemGroup>

</Project>
